from pathlib import Path

path = Path('scripts/apply-m6a-brush-tips.py')
text = path.read_text()
old = '''# Two color loops: remove radial-only clipping and use shared coverage.\nfor _ in range(2):\n    replace_once(\n        'src/gpu/baseline-raster-tile-store.ts',\n        "    const localYSquared = localY * localY;\\n    if (localYSquared >= 1) continue;\\n    for (let documentX = minX; documentX <= maxX; documentX += 1) {\\n      const localX = (documentX + 0.5 - dab.x) / radiusX;\\n      const distanceSquared = localX * localX + localYSquared;\\n      if (distanceSquared >= 1) continue;\\n      const tipCoverage =\\n        distanceSquared <= BASELINE_BRUSH_HARDNESS_SQUARED\\n          ? 1\\n          : clamp01(1 - smoothstep(BASELINE_BRUSH_HARDNESS, 1, Math.sqrt(distanceSquared)));",\n        "    if (Math.abs(localY) >= 1) continue;\\n    for (let documentX = minX; documentX <= maxX; documentX += 1) {\\n      const localX = (documentX + 0.5 - dab.x) / radiusX;\\n      const tipCoverage = brushTipCoverageV1(tipContext, dab, localX, localY);\\n      if (tipCoverage <= 0) continue;",\n    )\n'''
new = '''# Two color loops: rgba8 is nested one indentation level deeper than rgba16F.\nreplace_once(\n    'src/gpu/baseline-raster-tile-store.ts',\n    "      const localYSquared = localY * localY;\\n      if (localYSquared >= 1) continue;\\n      for (let documentX = minX; documentX <= maxX; documentX += 1) {\\n        const localX = (documentX + 0.5 - dab.x) / radiusX;\\n        const distanceSquared = localX * localX + localYSquared;\\n        if (distanceSquared >= 1) continue;\\n        const tipCoverage =\\n          distanceSquared <= BASELINE_BRUSH_HARDNESS_SQUARED\\n            ? 1\\n            : clamp01(1 - smoothstep(BASELINE_BRUSH_HARDNESS, 1, Math.sqrt(distanceSquared)));",\n    "      if (Math.abs(localY) >= 1) continue;\\n      for (let documentX = minX; documentX <= maxX; documentX += 1) {\\n        const localX = (documentX + 0.5 - dab.x) / radiusX;\\n        const tipCoverage = brushTipCoverageV1(tipContext, dab, localX, localY);\\n        if (tipCoverage <= 0) continue;",\n)\nreplace_once(\n    'src/gpu/baseline-raster-tile-store.ts',\n    "    const localYSquared = localY * localY;\\n    if (localYSquared >= 1) continue;\\n    for (let documentX = minX; documentX <= maxX; documentX += 1) {\\n      const localX = (documentX + 0.5 - dab.x) / radiusX;\\n      const distanceSquared = localX * localX + localYSquared;\\n      if (distanceSquared >= 1) continue;\\n      const tipCoverage =\\n        distanceSquared <= BASELINE_BRUSH_HARDNESS_SQUARED\\n          ? 1\\n          : clamp01(1 - smoothstep(BASELINE_BRUSH_HARDNESS, 1, Math.sqrt(distanceSquared)));",\n    "    if (Math.abs(localY) >= 1) continue;\\n    for (let documentX = minX; documentX <= maxX; documentX += 1) {\\n      const localX = (documentX + 0.5 - dab.x) / radiusX;\\n      const tipCoverage = brushTipCoverageV1(tipContext, dab, localX, localY);\\n      if (tipCoverage <= 0) continue;",\n)\n'''
if old not in text:
    raise SystemExit('target color-loop patch block not found')
path.write_text(text.replace(old, new, 1))
print('brush tip patcher anchors fixed')
