from pathlib import Path

path = Path('scripts/apply-m6a-brush-tips.py')
text = path.read_text()

old = '''# Two color loops: remove radial-only clipping and use shared coverage.\nfor _ in range(2):\n    replace_once(\n        'src/gpu/baseline-raster-tile-store.ts',\n        "    const localYSquared = localY * localY;\\n    if (localYSquared >= 1) continue;\\n    for (let documentX = minX; documentX <= maxX; documentX += 1) {\\n      const localX = (documentX + 0.5 - dab.x) / radiusX;\\n      const distanceSquared = localX * localX + localYSquared;\\n      if (distanceSquared >= 1) continue;\\n      const tipCoverage =\\n        distanceSquared <= BASELINE_BRUSH_HARDNESS_SQUARED\\n          ? 1\\n          : clamp01(1 - smoothstep(BASELINE_BRUSH_HARDNESS, 1, Math.sqrt(distanceSquared)));",\n        "    if (Math.abs(localY) >= 1) continue;\\n    for (let documentX = minX; documentX <= maxX; documentX += 1) {\\n      const localX = (documentX + 0.5 - dab.x) / radiusX;\\n      const tipCoverage = brushTipCoverageV1(tipContext, dab, localX, localY);\\n      if (tipCoverage <= 0) continue;",\n    )\n'''
new = '''# Two color loops: rgba8 is nested one indentation level deeper than rgba16F.\nreplace_once(\n    'src/gpu/baseline-raster-tile-store.ts',\n    "      const localYSquared = localY * localY;\\n      if (localYSquared >= 1) continue;\\n      for (let documentX = minX; documentX <= maxX; documentX += 1) {\\n        const localX = (documentX + 0.5 - dab.x) / radiusX;\\n        const distanceSquared = localX * localX + localYSquared;\\n        if (distanceSquared >= 1) continue;\\n        const tipCoverage =\\n          distanceSquared <= BASELINE_BRUSH_HARDNESS_SQUARED\\n            ? 1\\n            : clamp01(1 - smoothstep(BASELINE_BRUSH_HARDNESS, 1, Math.sqrt(distanceSquared)));",\n    "      if (Math.abs(localY) >= 1) continue;\\n      for (let documentX = minX; documentX <= maxX; documentX += 1) {\\n        const localX = (documentX + 0.5 - dab.x) / radiusX;\\n        const tipCoverage = brushTipCoverageV1(tipContext, dab, localX, localY);\\n        if (tipCoverage <= 0) continue;",\n)\nreplace_once(\n    'src/gpu/baseline-raster-tile-store.ts',\n    "    const localYSquared = localY * localY;\\n    if (localYSquared >= 1) continue;\\n    for (let documentX = minX; documentX <= maxX; documentX += 1) {\\n      const localX = (documentX + 0.5 - dab.x) / radiusX;\\n      const distanceSquared = localX * localX + localYSquared;\\n      if (distanceSquared >= 1) continue;\\n      const tipCoverage =\\n        distanceSquared <= BASELINE_BRUSH_HARDNESS_SQUARED\\n          ? 1\\n          : clamp01(1 - smoothstep(BASELINE_BRUSH_HARDNESS, 1, Math.sqrt(distanceSquared)));",\n    "    if (Math.abs(localY) >= 1) continue;\\n    for (let documentX = minX; documentX <= maxX; documentX += 1) {\\n      const localX = (documentX + 0.5 - dab.x) / radiusX;\\n      const tipCoverage = brushTipCoverageV1(tipContext, dab, localX, localY);\\n      if (tipCoverage <= 0) continue;",\n)\n'''
if old not in text:
    raise SystemExit('target color-loop patch block not found')
text = text.replace(old, new, 1)

old_same_dab = '''replace_once(\n    'src/gpu/baseline-paint-renderer.ts',\n    "    left.opacity === right.opacity &&\\n    baselineDabColorV1(left).every(",\n    "    left.opacity === right.opacity &&\\n    left.tipAssetIndex === right.tipAssetIndex &&\\n    JSON.stringify(left.tip ?? null) === JSON.stringify(right.tip ?? null) &&\\n    baselineDabColorV1(left).every(",\n)\n'''
new_same_dab = '''replace_once(\n    'src/gpu/baseline-paint-renderer.ts',\n    "    baselineDabStrokeOpacityV1(left) === baselineDabStrokeOpacityV1(right) &&\\n    baselineDabColorV1(left).every(",\n    "    baselineDabStrokeOpacityV1(left) === baselineDabStrokeOpacityV1(right) &&\\n    left.tipAssetIndex === right.tipAssetIndex &&\\n    JSON.stringify(left.tip ?? null) === JSON.stringify(right.tip ?? null) &&\\n    baselineDabColorV1(left).every(",\n)\n'''
if old_same_dab not in text:
    raise SystemExit('target sameDab patch block not found')
text = text.replace(old_same_dab, new_same_dab, 1)

old_present = '''replace_once(\n    'src/gpu/baseline-paint-renderer.ts',\n    "    this.#activeStroke.dabs.push(...delta);\\n    if (delta.length > 0) {\\n      if (operation !== 'paint') {",\n    "    this.#activeStroke.dabs.push(...delta);\\n    if (delta.some(baselineDabRequiresCanonicalTilePresentationV1)) {\\n      this.#activeStroke.canonicalTilePresentation = true;\\n    }\\n    if (delta.length > 0) {\\n      if (operation !== 'paint' || this.#activeStroke.canonicalTilePresentation) {",\n)\n'''
new_present = '''replace_once(\n    'src/gpu/baseline-paint-renderer.ts',\n    "    this.#activeStroke.dabs.push(...delta);\\n    if (delta.length > 0) {\\n      if (operation !== 'paint' || requiresCanonicalPaintPreview(delta)) {",\n    "    this.#activeStroke.dabs.push(...delta);\\n    if (delta.some(baselineDabRequiresCanonicalTilePresentationV1)) {\\n      this.#activeStroke.canonicalTilePresentation = true;\\n    }\\n    if (delta.length > 0) {\\n      if (\\n        operation !== 'paint' ||\\n        this.#activeStroke.canonicalTilePresentation ||\\n        requiresCanonicalPaintPreview(delta)\\n      ) {",\n)\n'''
if old_present not in text:
    raise SystemExit('target presentStroke patch block not found')
text = text.replace(old_present, new_present, 1)

old_tail = '''replace_once(\n    'src/gpu/baseline-paint-renderer.ts',\n    "        if (operation !== 'paint') {\\n          this.#patchCompositeTiles(",\n    "        if (operation !== 'paint' || active.canonicalTilePresentation) {\\n          this.#patchCompositeTiles(",\n)\n'''
new_tail = '''replace_once(\n    'src/gpu/baseline-paint-renderer.ts',\n    "        if (operation !== 'paint' || requiresCanonicalPaintPreview(missingTail)) {\\n          this.#patchCompositeTiles(",\n    "        if (\\n          operation !== 'paint' ||\\n          active.canonicalTilePresentation ||\\n          requiresCanonicalPaintPreview(missingTail)\\n        ) {\\n          this.#patchCompositeTiles(",\n)\n'''
if old_tail not in text:
    raise SystemExit('target finalize tail patch block not found')
text = text.replace(old_tail, new_tail, 1)

old_full = '''replace_once(\n    'src/gpu/baseline-paint-renderer.ts',\n    "        if (operation !== 'paint') {\\n          this.#patchCompositeTiles(\\n            planBaselineBrushTilesV1(frozenDabs, width, height)",\n    "        if (operation !== 'paint' || this.#activeStroke.canonicalTilePresentation) {\\n          this.#patchCompositeTiles(\\n            planBaselineBrushTilesV1(frozenDabs, width, height)",\n)\n'''
new_full = '''replace_once(\n    'src/gpu/baseline-paint-renderer.ts',\n    "        if (operation !== 'paint' || requiresCanonicalPaintPreview(frozenDabs)) {\\n          this.#patchCompositeTiles(\\n            planBaselineBrushTilesV1(frozenDabs, width, height)",\n    "        if (\\n          operation !== 'paint' ||\\n          this.#activeStroke.canonicalTilePresentation ||\\n          requiresCanonicalPaintPreview(frozenDabs)\\n        ) {\\n          this.#patchCompositeTiles(\\n            planBaselineBrushTilesV1(frozenDabs, width, height)",\n)\n'''
if old_full not in text:
    raise SystemExit('target finalize full patch block not found')
text = text.replace(old_full, new_full, 1)

path.write_text(text)
print('brush tip patcher anchors fixed')
